937 redesign
ONSdigital/sdc-waf-error-page pull request #1
Opened 2019-02-18 12:06 UTC by tgandrews

### What is changing
Change to match new design. But still has a couple of outstanding problems:
- [ ] Google analytics UA is missing
- [ ] How are we getting the browser and OS version?
- [ ] What browsers are we supporting?

### How to review
1. Ensure this matches the design

2019-02-18 13:28 UTC, tgandrews commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update WAF Error HTML to Fix it](https://trello.com/c/1grEBx0U/937-update-waf-error-html-to-fix-it)

2019-02-19 09:25 UTC, samiwel approved these changes
Content looks correct as per the design attached to the card. @ajmaddaford what's the process for updating this error page on the WAF?

2019-02-19 10:47 UTC, ajmaddaford requested changes
@tgandrews I'm waiting to hear back about whether the `{{ERROR-CODE}}` and `{{ERROR-ID}}` are used, I'll let you know as soon as I hear back.

2019-02-19 10:47 UTC, ajmaddaford commented on waf_error_page.html
> +    <!-- End Google Analytics -->
I think we should remove the Google Analytics code. The WAF error page is for all Survey Data Collection products and there is no combined Google Analytics account we could use here.

2019-02-19 10:47 UTC, ajmaddaford commented on waf_error_page.html
> +    </script>
These timeout values aren't needed.

2019-02-19 10:47 UTC, ajmaddaford commented on waf_error_page.html
> +                <h1 class="saturn u-fs-xl">An error has occurred</h1>
I thought all the planet based classes were removed?

2019-02-19 10:47 UTC, ajmaddaford commented on waf_error_page.html
> +            <div class="pluto">
Same as comment above about planet based classes.

2019-02-20 08:47 UTC, ajmaddaford requested changes

2019-02-20 08:47 UTC, ajmaddaford commented on waf_error_page.html
> +                  <div>{{ ERROR - CODE }} {{ ERROR - ID }}</div>
These need to be `{{ERROR-CODE}}` and `{{ERROR-ID}}` - without spaces.

2019-02-27 11:09 UTC, ajmaddaford approved these changes

2019-02-27 13:02 UTC, merged